### PR TITLE
[10.0][MIG] mrp_bom_current_stock

### PR DESCRIPTION
**Pull request by rgarnau**
No major changes.

This module depends on:
- [x] https://github.com/OCA/manufacture/pull/256

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]
:green_apple:

**Review by AaronHForgeFlow — COMMENTED** [review]
The setup folders should not be there yet, should they?

**Comment by AaronHForgeFlow** [comment]
Got error when printing the report:
image
Trace:

>   File "/home/odoo/build/OCA/manufacture-reporting/mrp_bom_current_stock/wizard/bom_route_current_stock.py", line 147, in _compute_qty_available_in_source_loc
    res = self.product_uom_id._compute_qty(
AttributeError: 'product.uom' object has no attribute '_compute_qty'
Error to render compiling AST
AttributeError: 'product.uom' object has no attribute '_compute_qty'
Template: 537
Path: /templates/t/t/t/div/t/table/tbody/tr[2]/td[5]/span[1]
Node: <span t-field="l.qty_available_in_source_loc"/>

**Comment by MiquelRForgeFlow** [comment]
@aheficent Fixed

**Comment by AaronHForgeFlow** [comment]
hidden :bug:

**Comment by MiquelRForgeFlow** [comment]
totally fixed now  😎

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Working fine now

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
