### PR TITLE
7.0 add serpents mrp operation webkit

### PR DESCRIPTION
**Pull request by gurneyalex**
port of the MP done on launchpad

### CODE REVIEW

**Comment by bwrsandman** [comment]
Is  Hemangini Patel on github? If not, let's assign someone to this PR.

**Comment by max3903** [comment]
@JayVora-SerpentCS shall we close this PR or you will fix this module ?

**Comment by pedrobaeza** [comment]
What is the status of this?

**Comment by JayVora-SerpentCS** [comment]
I do not have access of it unfortunately. Ours is #12

**Pull request closed without merging**
