### PR TITLE
[14.0][MIG] mrp_bom_structure_xlsx_level_1: Migration to 14.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 14.0

Please @pedrobaeza and @ernestotejeda can you review it?

@Tecnativa TT33397

### CODE REVIEW

**Review by ernestotejeda — COMMENTED** [review]
I can't see the print option while testing on runboat, do i miss a configuration or anything else?

image

**Comment by victoralmau** [comment]
> I can't see the print option while testing on runboat, do i miss a configuration or anything else?
> 
> image

Sorry and thanks, it's changed now.

**Review by flotho — APPROVED** [review]
functionnally tested on runoat.
LGTM

**Review by ernestotejeda — APPROVED** [review]

**Pull request merged**
