### PR TITLE
[8.0][REF] .travis.yml: Enable build for new runbot travis2docker structure

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Solves Issue https://github.com/OCA/runbot-addons/issues/115

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please use the new template with the matrix and activate Transifex at the same time.

**Review by moylop260 — APPROVED** [review]
👍 
Thanks!

**Review by gurneyalex — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@gurneyalex The new template is not put

**Comment by MiquelRForgeFlow** [comment]
The problem in https://github.com/OCA/manufacture-reporting/pull/8 is not solved because like @pedrobaeza said, the template is not put.

cc @jbeficent @gurneyalex @moylop260

**Comment by JordiBForgeFlow** [comment]
@mreficent can yoy add it?

**Comment by MiquelRForgeFlow** [comment]
Yes. Done in https://github.com/OCA/manufacture-reporting/pull/20

**Comment by moylop260** [comment]
For record, (offtopic of new template or not)

The https://github.com/OCA/manufacture-reporting/pull/8 is not fixed because the branch is not updated with new change(1)

After affects the base branch even you will need update the branch of your PR to get last changes and fixes.

Like as Alex comment https://github.com/OCA/manufacture-reporting/pull/8#issuecomment-274317545 requested you

I mean, if we merge https://github.com/OCA/manufacture-reporting/pull/20 and you don't update your PR branch you will have the same issue yet

(1) https://github.com/Eficent/manufacture-reporting/blob/59467e7da00ac2367c9e0e36afed0c1aeee9e059/.travis.yml#L17

**Pull request merged**
