### PR TITLE
[14.0][IMP] mrp_bom_current_stock: multiple quantity and available check

### PR DESCRIPTION
**Pull request by DavidJForgeFlow**
This allows to see the available quantity of the desired product and the amount quantity available for making from stock. Also adds a MO recreation to see the same values as if you were making a MO.

@ForgeFlow

### CODE REVIEW

**Comment by BernatPForgeFlow** [comment]
Functional review looks good! Nice improvements!

**Review by BernatPForgeFlow — APPROVED** [review]

**Review by PauBForgeFlow — APPROVED** [review]
LGTM

**Comment by JordiBForgeFlow** [comment]
@DavidJForgeFlow Can you check why tests fail?

**Comment by BernatPForgeFlow** [comment]
> @DavidJForgeFlow Can you check why tests fail?

Fixed!

**Comment by bosd** [comment]
Can this be merged?

**Comment by JordiBForgeFlow** [comment]
@LoisRForgeFlow Can you merge?

**Comment by LoisRForgeFlow** [comment]
@DavidJForgeFlow Can you forward port to newer versions?

**Comment by hparfr** [comment]
@LoisRForgeFlow  There is a change in the dependencies; why not bump "major" ?

**Comment by LoisRForgeFlow** [comment]
@hparfr you are right, I didn't realize of that

**Pull request merged**
