### PR TITLE
[13.0][MIG] mrp_bom_structure_report_level_1

### PR DESCRIPTION
**Pull request by JoanSForgeFlow**
Standard mrp_bom_structure_report_level_1 migration to v13.

cc~ @ForgeFlow @MiquelRForgeFlow

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
Split commit into pre-commit and migration one

**Review by AdriaGForgeFlow — COMMENTED** [review]
Small comment after code review

**Review by AdriaGForgeFlow — APPROVED** [review]
Tested on local :+1:

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Pull request merged**
