### PR TITLE
[12.0][MIG] mrp_bom_structure_html

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Standard migration

CC @Eficent

### CODE REVIEW

**Review by HaraldPanten — CHANGES_REQUESTED** [review]
Functional review:

Internal server error when trying to preview on runbot.

It's not working in local environment as well. That's the error that console shows.

`raise ValueError('External ID not found in the system: %s' % xmlid)
odoo_1                    | ValueError: External ID not found in the system: mrp.mrp_bom_structure_report - - -`

**Comment by HviorForgeFlow** [comment]
Fixed now!

**Review by HaraldPanten — APPROVED** [review]
Functional review 👍

**Comment by HviorForgeFlow** [comment]
This functionality is already in Odoo core, closing PR, thanks for reviewing

**Pull request closed without merging**
