### PR TITLE
[10.0][FIX]flattened bom

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Backporting fixes done in https://github.com/OCA/manufacture-reporting/pull/48
ping @lreficent @hveficent

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@aheficent can you open another PR to fix travis definition in v10?

**Comment by AaronHForgeFlow** [comment]
> @aheficent can you open another PR to fix travis definition in v10?

Sure: https://github.com/OCA/manufacture-reporting/pull/67

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
