### PR TITLE
[11.0][ADD] mrp_bom_structure_report

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
This is a back port from mrp structure report incorpored by Odoo in v12.0

The module includes three different kind of reports:
1. BoM Structure & Cost Report
2. BoM Structure Report
3. BoM Cost Report

### CODE REVIEW

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
Functional review:
* Print Unfolded is not taking into account quantities.

Nitpicking:
* Use capital letter at the beginning of any word in print buttons.

**Comment by AdriaGForgeFlow** [comment]
> Functional review:
> 
> * Print Unfolded is not taking into account quantities.
> 
> Nitpicking:
> 
> * Use capital letter at the beginning of any word in print buttons.

In v12.0, in Odoo, Print unfolded has the same behaviour. Maybe this should be an improvement to be done since it make sense to print the same amount than the one that has been introduced by the user in the UI.

**Review by marcelofrare — APPROVED** [review]
Tested on my local installation. Ok

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
