### PR TITLE
[12.0][MIG] mrp_bom_structure_xlsx_level_1

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
:man_facepalming: 

image

**Comment by MiquelRForgeFlow** [comment]
This PR was not ready to be reviewed.

**Review by MiquelRForgeFlow — COMMENTED** [review]
:+1:

**Comment by MiquelRForgeFlow** [comment]
@lreficent please, remove wip tag, it's ready to review.

**Review by HviorForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
I cannot see the option in runbot:
image

**Comment by MiquelRForgeFlow** [comment]
> I cannot see the option in runbot:

Because you have to install the module in the runbot first.

**Review by LoisRForgeFlow — APPROVED** [review]
How weird that it is not pre-installed...

Anyway, LGTM

**Pull request merged**
