### PR TITLE
[14.0][MIG] mrp_bom_current_stock

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**

### CODE REVIEW

**Comment by BernatPForgeFlow** [comment]
@ForgeFlow @LoisRForgeFlow @JoanMForgeFlow @AaronHForgeFlow @mariadforgeflow

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Review by JoanMForgeFlow — APPROVED** [review]
LGTM!

**Review by LoisRForgeFlow — APPROVED** [review]
Functional review :+1:

**Pull request merged**
