### PR TITLE
[ADD]Added mrp_repair_webkit.

### PR DESCRIPTION
**Pull request by JayVora-SerpentCS**

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
gurneyalex/manufacture-reporting

**Comment by JayVora-SerpentCS** [comment]
Ref OCA/manufacture-reporting/pull/3

**Comment by JayVora-SerpentCS** [comment]
OCA BOT,

This was committed by only @JayVora-SerpentCS user credentials. However, the local config name was Hemangini Patel.

Please accept.

Thanks.

**Comment by pedrobaeza** [comment]
What is the status of this?

**Comment by JayVora-SerpentCS** [comment]
Went out of Radar, Did very minor edits. Don't know what travis does not find. Please help.

**Comment by LoisRForgeFlow** [comment]
Stale

**Pull request closed without merging**
