### PR TITLE
[11.0][IMP] mrp_flattened_bom_xlsx: cover multi level bom case 

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Previously the computation on multi level BoMs was not correct. Added tests.

cc @hveficent @jbeficent

### CODE REVIEW

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
@lreficent It would be convenient to settle how we use product quantity related to top parent.
For example if I change from 1 -> 10 below:
image
I receive that result:
image
I think just forcing top product quantity to 1 in report is fine.

BTW I appreciate the face wash. Thanks :smile:

**Comment by LoisRForgeFlow** [comment]
@hveficent I made explicit that the bom method computes the unit requirements in the default UoM.

**Review by HviorForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Technical review

**Pull request merged**
