### PR TITLE
[15.0][MIG] mrp_bom_structure_xlsx

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
To use this module, you need to:

Go to the Bill of Materials form or list views, press 'Print > Export BoM
Structure to Excel'.

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
Functional LG

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Code review

**Pull request merged**
