### PR TITLE
[11.0][FIX] mrp_bom_current_stock: UoM compute quantity error

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
CC @jbeficent

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Obvious :smile: :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: LGTM

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
if this is true, then do not call the convert method at all.

Could you add some tests?

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
You should update the qty available computation, now it is incorrect. I was reproducing your test BoMs locally and if found this:

image

image

So, what's available is 10 units (not 120 dozens), I guess the conversion is reversed (10 [units] * 12 [units/dozens] instead of 10 [units] / 12 [units/dozens]).

**Comment by HviorForgeFlow** [comment]
@lreficent it seems ready

**Comment by HviorForgeFlow** [comment]
ping @lreficent :smile:

**Comment by LoisRForgeFlow** [comment]
Problem still persists :sweat:

**Review by LoisRForgeFlow — APPROVED** [review]
Looks good now :+1:

**Pull request merged**
