### PR TITLE
[16.0][IMP] mrp_bom_structure_xlsx: Add tests

### PR DESCRIPTION
**Pull request by victoralmau**
Add tests

Please @chienandalu and @pilarvargas-tecnativa can you review it?

@Tecnativa TT47840

### CODE REVIEW

**Review by pilarvargas-tecnativa — APPROVED** [review]
thanks!

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Comment by LoisRForgeFlow** [comment]
@victoralmau could you fwport this to v17?

**Pull request merged**
