### PR TITLE
[9.0][REF] .travis.yml: Enable build for new runbot travis2docker structure

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Solves https://github.com/OCA/runbot-addons/issues/115

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please use the new template with the matrix and activate Transifex at the same time.

**Comment by JordiBForgeFlow** [comment]
Where is the template? How to activate Transifex? Any documentation?

**Comment by pedrobaeza** [comment]
https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml

and 

https://github.com/OCA/maintainer-quality-tools/issues/194

**Review by pedrobaeza — APPROVED** [review]
If Travis goes well

**Review by LoisRForgeFlow — APPROVED** [review]
Travis OK :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: hurray!

**Comment by pedrobaeza** [comment]
Runbot is still failing. Is there any addon in the repo already?

**Comment by AaronHForgeFlow** [comment]
No, there are no addons yet.

Runbot logs are showing: Nothing to test- exiting early.

**Comment by pedrobaeza** [comment]
OK, let's merge

**Pull request merged**
