### PR TITLE
[11.0][MIG] mrp_bom_structure_xlsx_level_1

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Depends on: #33

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Please, rebase the PR :)

**Comment by JordiBForgeFlow** [comment]
@hveficent Please rebase.

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@hveficent please respect commit history.

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM :+1:

**Pull request merged**
