### PR TITLE
[12.0][MIG] mrp_bom_structure_report_level_1

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
This is not working, it is printing the exact same report as default product structure one:

default bom structure
image

bom structure (level 1)
image

**Comment by MiquelRForgeFlow** [comment]
This PR was not ready to be reviewed.

**Comment by LoisRForgeFlow** [comment]
Then signal it in some way with any word :wink:

**Review by MiquelRForgeFlow — COMMENTED** [review]
:+1:

**Comment by MiquelRForgeFlow** [comment]
@lreficent please, remove wip tag, it's ready to review.

**Review by HviorForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Tested in runbot.

image

**Comment by HviorForgeFlow** [comment]
@lreficent error is related to mrp_bom_location. I took a fast look on it and a fast fix is a glue module. I'm figuring out how we can handle it without workarounds.

**Comment by HviorForgeFlow** [comment]
@lreficent could you update your review? Thanks!

**Review by LoisRForgeFlow — APPROVED** [review]
Now it works, thanks!

**Pull request merged**
