### PR TITLE
[17.0][MIG] mrp_bom_structure_report_level_1

### PR DESCRIPTION
**Pull request by AnaisLForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@AnaisLForgeFlow you must have done something weird during the rebase of this branch.

image

Could you check?

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! code and functional review 👍🏿 
great additions to the readme IHMO 😄

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM!

**Pull request merged**
