### PR TITLE
7.0 add serpents mrp repair webkit

### PR DESCRIPTION
**Pull request by gurneyalex**
port of launchpad MP.

### CODE REVIEW

**Comment by bwrsandman** [comment]
Is  Hemangini Patel on github? If not, let's assign someone to this PR.

**Comment by bwrsandman** [comment]
@gurneyalex What's the status on this.

**Comment by max3903** [comment]
@JayVora-SerpentCS shall we close this PR or will you fix this module?

**Comment by JayVora-SerpentCS** [comment]
@max3903 Surely, will fix it!

**Comment by JayVora-SerpentCS** [comment]
It was taken from Launchpad I believe! So we will need access.

**Comment by max3903** [comment]
@JayVora-SerpentCS You can pull this branch, push it to your repo, make another PR and reference it here.

**Comment by JayVora-SerpentCS** [comment]
@meet_scs Please handle with Hemangini.

**Comment by ghost** [comment]
Hello Everyone,

We will start working on it by tomorrow.

Thanks.

**Comment by JayVora-SerpentCS** [comment]
PR #12 has been added. We are working on the Travis and will correct some code as per the https://github.com/gurneyalex/manufacture-reporting/tree/7.0-add_serpents_mrp_repair_webkit
Thanks.

**Comment by JayVora-SerpentCS** [comment]
Please help to pass this travis error : https://travis-ci.org/OCA/manufacture-reporting/jobs/98669013

**Comment by pedrobaeza** [comment]
What is the status of this?

**Comment by JayVora-SerpentCS** [comment]
@MeetSCS made a mistake. you should have made a PR for https://github.com/gurneyalex/manufacture-reporting/tree/7.0-add_serpents_mrp_repair_webkit.
If @pedrobaeza allows, we are fine. Otherwise, let us work based on #12.

**Pull request closed without merging**
